#!/bin/bash

CURDIR=`pwd`

cd src/Mint-L
./build-themes.py

cd $CURDIR

sudo rm -rf /usr/share/themes/Mint-L
sudo cp -R usr/share/themes/Mint-L /usr/share/themes/Mint-L

# Force refresh
gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-L-Blue'
gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-L'

gsettings set org.cinnamon.theme name 'Mint-L-Blue'
gsettings set org.cinnamon.theme name 'Mint-L'
