#!/bin/bash

CURDIR=`pwd`

cd src/Mint-Y-Legacy
./build-themes.py

cd $CURDIR

sudo rm -rf /usr/share/themes/Mint-Y-Legacy
sudo cp -R usr/share/themes/Mint-Y-Legacy /usr/share/themes/Mint-Y-Legacy

# Force refresh
gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-Y-Legacy-Blue'
gsettings set org.cinnamon.desktop.interface gtk-theme 'Mint-Y-Legacy'
